name: Code Style Linter # workflow的名称

on: [push, pull_request] # 触发条件：在push代码或创建/更新Pull Request时运行

jobs:
  build: # 定义一个名为build的job
    runs-on: ubuntu-latest # 指定运行在最新的Ubuntu系统上

    steps: # 定义具体的执行步骤
      # 步骤1：将仓库的代码拉取到虚拟机环境中
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤2：设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # 使用最新的3.x版本Python

      # 步骤3：安装依赖（就是requirements.txt里的flake8）
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 步骤4：运行Linter检查
      - name: Run flake8
        run: |
          flake8 . --count --show-source --statistics