name: CI Pipeline with Lint and Test 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 步骤2：设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 步骤3：安装依赖
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 步骤4：运行Linter检查
      - name: Run flake8
        run: |
          flake8 . --count --show-source --statistics

      # 步骤5：【新增】运行单元测试
      - name: Run tests with pytest
        run: |
          pytest